# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- release

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: nzfurs
  imageName: 'furconz'
  isPullRequest: eq(variables['Build.Reason'], 'PullRequest')

steps:
- script: |
    docker build -f Dockerfile -t $(dockerId)/$(imageName):$(build.buildId) -t $(dockerId)/$(imageName):latest .
  displayName: Build Docker Container
- script: |
    docker tag $(dockerId)/$(imageName):$(build.buildId) $(dockerId)/$(imageName):stable
  condition: in(variables['Build.SourceBranch'], 'refs/heads/release')
  displayName: Tag release image with :stable
- script: |
    docker login -u $(dockerHubId) -p $(dockerHubPassword)
    docker push $(dockerId)/$(imageName)
  condition: not(${{ variables.isPullRequest }})
  displayName: Publish to Docker Hub
